### ISSUE TITLE
Can add timestamps for FCM-listen 

### ISSUE THREAD

**Issue by C74K** [liamcottle/rustplus.js#24]
would be able to add timestamps for fcm-listen?

**Comment by liamcottle** [comment]
Hi, could you give me an example of what you mean? I'm assuming you just want a prefixed timestamp in the console when a new entry is added to the log.

**Comment by C74K** [comment]
yes.

**Comment by liamcottle** [comment]
Implemented in [`v2.3.0`](https://github.com/liamcottle/rustplus.js/releases/tag/v2.3.0)
