### ISSUE TITLE
See group chat message

### ISSUE THREAD

**Issue by Umberghost** [liamcottle/rustplus.js#26]
Us there any way to see whenever a game chat message has been sent (and the content on that data)?

Thanks in advance, been using the npmjs package for a week and it's sooo good, great work!

**Comment by liamcottle** [comment]
Thanks for the feedback! Unfortunately that's not possible though, as the Rust+ app only allows access to team messages.

**Comment by Umberghost** [comment]
And with the current api, can you get the current team chat? Didn't see any method for it.

**Comment by liamcottle** [comment]
You can grab the team chat history like so:

```
rustplus.sendRequest({
    getTeamChat: {
        
    },
}, (message) => {
    console.log(message);
});
```

or with promises:

```
rustplus.sendRequestAsync({
    getTeamChat: {},
}).then((response) => {

    // AppResponse
    console.log(response);

}).catch((error) => {

    // AppError or Error('Timeout');
    console.log(error);

});
```
