### ISSUE TITLE
Issue with getEntityInfo?

### ISSUE THREAD

**Issue by FerretCode** [liamcottle/rustplus.js#27]
I'm testing getEntityInfo with an ID that someone gave me that they got from FCM, but I'm getting a response like this back: 
`getEntityInfo response message: {"response":{"seq":1,"error":{"error":"not_found"}}}`

Here's the code I'm using:

```javascript
instance.getEntityInfo(40402673, (message) => {
    console.log("getEntityInfo response message: " + JSON.stringify(message));
    return true;
});
```

**Comment by liamcottle** [comment]
Hi!

> with an ID that someone gave me

You will get `not_found` in these situations, and maybe more.

- Your `playerId` or `playerToken` is wrong
- The `entityId` does not exist on the server
- The `entityId` requires TC access, and you aren't authed with it.
