### ISSUE TITLE
[Question]fcm-listen in program

### ISSUE THREAD

**Issue by 4vent** [liamcottle/rustplus.js#32]
How will the program detect that a new entity has registered or that I have been killed?

**Comment by C74K** [comment]
> How will the program detect that a new entity has registered or that I have been killed?
read it directly from server

**Comment by liamcottle** [comment]
You can use the [push-receiver](https://github.com/MatthieuLemoine/push-receiver) package directly if you want to listen to fcm notifications in your own code.
