### ISSUE TITLE
RUST seems to have added new validation mechanisms

### ISSUE THREAD

**Issue by Arcaneing** [liamcottle/rustplus.js#40]
Certain servers can establish connections through APP, but using JS causes connection timeout exceptions. For example .CO EU MEDIUM(192.248.164.111:28085)
I'm not sure if it's because it uses some trick to hide the real address and port of the API
![image](https://user-images.githubusercontent.com/36686585/161444361-4fe3ec14-8f72-40fd-b649-5777ac33b17e.png)
![image](https://user-images.githubusercontent.com/36686585/161444475-1c750493-6113-4028-828f-98ac539d1984.png)
How can I solve this problem

**Comment by Arcaneing** [comment]
BUT I CAN USING RUST+ APP TO CONNECT THIS SERVER
![image](https://user-images.githubusercontent.com/36686585/161444590-142c212a-844c-4291-a9b1-575626cf2c6b.png)

**Comment by Arcaneing** [comment]
now,i'm sure that this server's ip and port is right.
![image](https://user-images.githubusercontent.com/36686585/161495313-3b74d860-05d7-4750-b9c0-ac71b8e2aa47.png)

But why just can connected with Rust+ APP

**Comment by liamcottle** [comment]
Try via a residential IP address. I'm assuming you are trying to run your code via a server host, and some servers use DDoS protection services which block IPs from known data centres / server hosting providers.
