### ISSUE TITLE
New camera update released

### ISSUE THREAD

**Issue by VTarakanov** [liamcottle/rustplus.js#52]
Are there plans to add camera interaction, if possible? Right now, this feature is in the rust plus **app**.

**Comment by olijeffers0n** [comment]
I know this is being worked on however it is not implemented very simply so will take time to reverse engineer.

**Comment by jonmaxwell** [comment]
I've resurrected the old code and am getting "unhandled" errors... We just need to know the request path & params and we should be good.

**Comment by olijeffers0n** [comment]
It’s not that simple, trust me. Watch this space though

**Comment by liquidthex** [comment]
I am so excited I really hope this can be figured out!

**Comment by jonmaxwell** [comment]
I believe I got the data working, now just onto the ray rendering

**Comment by olijeffers0n** [comment]
There is now a PR that closes this issue

**Comment by liamcottle** [comment]
Released in v2.4.0
