### ISSUE TITLE
Code Examples For Smart Alarms?

### ISSUE THREAD

**Issue by GreanDev** [liamcottle/rustplus.js#62]
Are there any code examples for how to process smart alarms?

running getInfo on the entityId of a smartAlarm doesn't return the message, And its not shown in the FCM notification either, Am I missing something?

**Comment by liamcottle** [comment]
You'll need to manage your own FCM notification listener to get the custom smart alarm messages.

Here's some relevant info about smart alarm notifications: https://github.com/liamcottle/rustplus.js/issues/17#issuecomment-796466975
