### ISSUE TITLE
An API push-receiver relies on will be deprecated in June

### ISSUE THREAD

**Issue by ghost** [liamcottle/rustplus.js#65]
According to this [issue](https://github.com/MatthieuLemoine/push-receiver/issues/68), push-receiver calls https://fcm.googleapis.com/fcm/connect/subscribe, which will be removed on June 20th this year. There's a replacement library, [Arcana](https://aracna.dariosechi.it/), which supposedly does everything push-receiver can do.

**Comment by Versette** [comment]
This fork uses the updated endpoints: https://github.com/javajuice1337/push-receiver-v2
So I guess that it could be used as a more drop-in replacement.

**Comment by liamcottle** [comment]
Fixed in v2.5.0
